### ISSUE TITLE
Fail extracting entrypoint

### ISSUE THREAD

**Issue by Damtev** [UnitTestBot/java-compilation-database#197]
Running `org.jacodb.analysis.graph.JcApplicationGraphImpl#methodOf` for the method `jdk.net.UnixDomainPrincipal#toString` leads to the exception:

```java
java.lang.StringIndexOutOfBoundsException: String index out of range: 39
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1513)
	at org.objectweb.asm.Type.getArgumentTypes(Type.java:302)
	at org.jacodb.impl.cfg.RawInstListBuilder.getBsmHandleArg(RawInstListBuilder.kt:1051)
	at org.jacodb.impl.cfg.RawInstListBuilder.buildInvokeDynamicInsn(RawInstListBuilder.kt:1072)
	at org.jacodb.impl.cfg.RawInstListBuilder.buildInstructions(RawInstListBuilder.kt:223)
	at org.jacodb.impl.cfg.RawInstListBuilder.build(RawInstListBuilder.kt:199)
	at org.jacodb.impl.features.classpaths.MethodInstructionsFeature.rawInstList(MethodInstructionsFeature.kt:53)
	at org.jacodb.impl.bytecode.JcMethodImpl.getRawInstList(JcMethodImpl.kt:84)
	at org.jacodb.impl.features.classpaths.MethodInstructionsFeature.instList(MethodInstructionsFeature.kt:46)
	at org.jacodb.impl.bytecode.JcMethodImpl.getInstList(JcMethodImpl.kt:93)
	at org.jacodb.impl.features.classpaths.MethodInstructionsFeature.flowGraph(MethodInstructionsFeature.kt:42)
	at org.jacodb.impl.bytecode.JcMethodImpl.flowGraph(JcMethodImpl.kt:88)
	at org.jacodb.analysis.graph.JcApplicationGraphImpl.entryPoint(JcApplicationGraphImpl.kt:64)
```

**Comment by lehvolk** [comment]
Can't reproduce on develop branch. Feel free to reopen
